---
- name: "Install PHP, PHP-FPM, PHP-CLI"
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-cli
  notify: "Restart PHP5-FPM"

- name: "Install PHP Extensions"
  apt: pkg={{ item }} state=latest
  with_items: php_extensions
  notify: "Restart PHP5-FPM"

- name: "Install PHP Dev-Extensions"
  apt: pkg={{ item }} state=latest
  with_items: php_extensions
  when: "'development' in group_names"
  notify: "Restart PHP5-FPM"

- name: "Global php.ini Configuration"
  template: >
    src=global.ini.j2
    dest=/etc/php5/mods-available/global.ini
  notify: "Restart PHP5-FPM"

- name: "Enable Global php.ini Configuration"
  command: php5enmod -s ALL global
  notify: "Restart PHP5-FPM"

- name: "Create error_log directories"
  file: >
    path=/var/log/php/{{ item.name }}
    owner={{ item.user|default(fpm_default_user) }}
    group={{ item.group|default(fpm_default_group) }}
    state=directory
    mode=0750
  with_items: php_pools

- name: "Register error_log rotations"
  template: >
    src=logrotate.j2
    dest=/etc/logrotate.d/php-fpm-{{ item.name }}
  with_items: php_pools

- name: "Configure FPM Pools"
  template: >
    src=pool.conf.j2
    dest=/etc/php5/fpm/pool.d/{{ item.name }}.conf
  with_items: php_pools
  notify: "Restart PHP5-FPM"
